run:
  timeout: 2m
  tests: false

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gofmt
    - goimports
  disable:
    - typecheck

issues:
  exclude-rules:
  - path: /
    linters:
    - typecheck

# issues:
  # exclude-use-default: false
#   exclude-rules:
#   - path: internal/auth/validation.go
#   linters:
#     - typecheck
